# Generated by Django 4.1.5 on 2023-03-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=70)),
                ('genero', models.CharField(max_length=30)),
                ('fecha_de_estreno', models.DateField()),
                ('tipo_de_juego', models.CharField(max_length=60)),
                ('caratula', models.ImageField(blank=b'I01\n', null=b'I01\n', upload_to='juegos')),
            ],
        ),
    ]
